stock-ticker: StockApiClient Class Reference
StockApiClient Class Reference
Handles fetching stock data and periodic updates from a remote API.
#include <StockApiClient.h>
Signals
void stockDataUpdated (const StockData &data)
Emitted when stock data is updated.
void errorOccurred (const QString &message)
Emitted when an error occurs.
Public Member Functions
StockApiClient (QObject *parent=nullptr)
Constructs a StockApiClient object.
virtual ~StockApiClient ()
virtual void fetchStockData (const std::string &symbol)
Fetches stock data for a given symbol.
virtual void setWatchlist (const Watchlist &watchlist)
Sets the watchlist of stock symbols.
virtual void startUpdates (int intervalMs=5000)
Starts periodic updates for the watchlist.
virtual void stopUpdates ()
Stops periodic updates.
Private Slots
void onReplyFinished (QNetworkReply *reply)
Handles finished network replies.
void onTimeout ()
Handles update timer timeouts.
Private Member Functions
void parseResponse (const QByteArray &response, const std::string &symbol)
Parses the API response and emits stockDataUpdated.
Private Attributes
QNetworkAccessManager m_networkManager
Manages network requests.
QTimer m_updateTimer
Timer for periodic updates.
Watchlist m_watchlist
List of stock symbols to watch.
Detailed Description
Handles fetching stock data and periodic updates from a remote API.
Definition at line 19 of file StockApiClient.h.
Constructor & Destructor Documentation
StockApiClient()
StockApiClient::StockApiClient (QObject * parent = nullptr) explicit
Constructs a StockApiClient object.
Parameters
parent The parent QObject.
Definition at line 8 of file StockApiClient.cpp.
    : QObject(parent) {
    connect(&m_networkManager, &QNetworkAccessManager::finished,
            this, &StockApiClient::onReplyFinished);
}
References m_networkManager, and onReplyFinished().
~StockApiClient()
StockApiClient::~StockApiClient () virtual default
Member Function Documentation
errorOccurred
void StockApiClient::errorOccurred (const QString & message) signal
Emitted when an error occurs.
Parameters
message The error message.
Referenced by onReplyFinished(), parseResponse(), and StockTickerWidget::StockTickerWidget().
fetchStockData()
void StockApiClient::fetchStockData (const std::string & symbol) virtual
Fetches stock data for a given symbol.
Parameters
symbol The stock symbol to fetch data for.
Definition at line 16 of file StockApiClient.cpp.
{
    QString url = QString("https://query1.finance.yahoo.com/v8/finance/chart/%1?interval=1m&range=1d")
                  .arg(QString::fromStdString(symbol));
    QNetworkRequest request(url);
    m_networkManager.get(request);
}
References m_networkManager.
Referenced by onTimeout().
onReplyFinished
void StockApiClient::onReplyFinished (QNetworkReply * reply) private slot
Handles finished network replies.
Parameters
reply The finished QNetworkReply.
Definition at line 40 of file StockApiClient.cpp.
{
    if (reply->error() != QNetworkReply::NoError) {
        emit errorOccurred(reply->errorString());
        reply->deleteLater();
        return;
    }
    QByteArray response = reply->readAll();
    std::string symbol = reply->url().toString().split('/').last().toStdString();
    parseResponse(response, symbol);
    reply->deleteLater();
}
References errorOccurred(), and parseResponse().
Referenced by StockApiClient().
onTimeout
void StockApiClient::onTimeout () private slot
Handles update timer timeouts.
Definition at line 54 of file StockApiClient.cpp.
{
    for (const auto& symbol : m_watchlist) {
        fetchStockData(symbol);
    }
}
References fetchStockData(), and m_watchlist.
Referenced by startUpdates().
parseResponse()
void StockApiClient::parseResponse (const QByteArray & response, const std::string & symbol) private
Parses the API response and emits stockDataUpdated.
Parameters
response The raw API response.
symbol The stock symbol.
Definition at line 60 of file StockApiClient.cpp.
{
    QJsonDocument doc = QJsonDocument::fromJson(response);
    if (doc.isNull()) {
        emit errorOccurred("Invalid JSON response");
        return;
    }
    QJsonObject chart = doc.object()["chart"].toObject();
    QJsonArray resultArray = chart["result"].toArray();
    if (resultArray.isEmpty()) {
        emit errorOccurred("No result in response");
        return;
    }
    QJsonObject result = resultArray.first().toObject();
    QJsonObject meta = result["meta"].toObject();
    QJsonArray quoteArray = result["indicators"].toObject()["quote"].toArray();
    if (quoteArray.isEmpty()) {
        emit errorOccurred("No quote data in response");
        return;
    }
    QJsonObject indicators = quoteArray.first().toObject();
    QJsonArray closePrices = indicators["close"].toArray();
    StockData data;
    data.symbol = symbol;
    data.price = meta["regularMarketPrice"].toDouble();
    data.change = meta["regularMarketChange"].toDouble();
    data.changePercent = meta["regularMarketChangePercent"].toDouble();
    data.timestamp = meta["regularMarketTime"].toInt();
    // Get last 10 close prices for chart
    int startIdx = std::max<int>(0, closePrices.size() - 10);
    for (int i = startIdx; i < closePrices.size(); ++i) {
        if (!closePrices[i].isNull())
            data.history.push_back(closePrices[i].toDouble());
    }
    emit stockDataUpdated(data);
}
References StockData::change, StockData::changePercent, errorOccurred(), StockData::history, StockData::price, stockDataUpdated(), StockData::symbol, and StockData::timestamp.
Referenced by onReplyFinished().
setWatchlist()
void StockApiClient::setWatchlist (const Watchlist & watchlist) virtual
Sets the watchlist of stock symbols.
Parameters
watchlist The list of stock symbols to watch.
Definition at line 24 of file StockApiClient.cpp.
{
    m_watchlist = watchlist;
}
References m_watchlist.
Referenced by StockTickerWidget::setWatchlist().
startUpdates()
void StockApiClient::startUpdates (int intervalMs = 5000) virtual
Starts periodic updates for the watchlist.
Parameters
intervalMs Update interval in milliseconds (default 5000).
Definition at line 28 of file StockApiClient.cpp.
{
    m_updateTimer.setInterval(intervalMs);
    connect(&m_updateTimer, &QTimer::timeout, this, &StockApiClient::onTimeout);
    m_updateTimer.start();
    // Immediately fetch first set of data
    onTimeout();
}
References m_updateTimer, and onTimeout().
Referenced by StockTickerWidget::setWatchlist().
stockDataUpdated
void StockApiClient::stockDataUpdated (const StockData & data) signal
Emitted when stock data is updated.
Parameters
data The updated stock data.
Referenced by parseResponse(), and StockTickerWidget::StockTickerWidget().
stopUpdates()
void StockApiClient::stopUpdates () virtual
Stops periodic updates.
Definition at line 36 of file StockApiClient.cpp.
{
    m_updateTimer.stop();
}
References m_updateTimer.
Member Data Documentation
m_networkManager
QNetworkAccessManager StockApiClient::m_networkManager private
Manages network requests.
Definition at line 74 of file StockApiClient.h.
Referenced by fetchStockData(), and StockApiClient().
m_updateTimer
QTimer StockApiClient::m_updateTimer private
Timer for periodic updates.
Definition at line 75 of file StockApiClient.h.
Referenced by startUpdates(), and stopUpdates().
m_watchlist
Watchlist StockApiClient::m_watchlist private
List of stock symbols to watch.
Definition at line 76 of file StockApiClient.h.
Referenced by onTimeout(), and setWatchlist().
The documentation for this class was generated from the following files:
/media/psanodiya/workspace/cpp/stock-ticker/include/StockApiClient.h
/media/psanodiya/workspace/cpp/stock-ticker/src/StockApiClient.cpp