stock-ticker: StockTickerWidget Class Reference
StockTickerWidget Class Reference
Main widget for displaying stock data and charts.
#include <StockTickerWidget.h>
Public Member Functions
StockTickerWidget (QWidget *parent=nullptr)
Constructs a StockTickerWidget.
~StockTickerWidget ()
void setWatchlist (const Watchlist &watchlist)
Sets the watchlist of stock symbols.
Private Slots
void updateStockData (const StockData &data)
Updates the display when new stock data arrives.
void handleError (const QString &message)
Handles errors from the API client.
void updateDisplay ()
Updates the display widget.
Private Member Functions
QString formatStockInfo (const StockData &data) const
Formats stock info for display.
Private Attributes
StockApiClient m_apiClient
API client for fetching stock data.
QTextEdit * m_display
Display widget for stock info.
Watchlist m_watchlist
List of stock symbols to watch.
std::map< std::string, StockData > m_stockData
Map of symbol to StockData.
Detailed Description
Main widget for displaying stock data and charts.
Definition at line 22 of file StockTickerWidget.h.
Constructor & Destructor Documentation
StockTickerWidget()
StockTickerWidget::StockTickerWidget (QWidget * parent = nullptr) explicit
Constructs a StockTickerWidget.
Parameters
parent The parent widget.
Definition at line 7 of file StockTickerWidget.cpp.
    : QWidget(parent) {
    QVBoxLayout* layout = new QVBoxLayout(this);
    m_display = new QTextEdit(this);
    m_display->setReadOnly(true);
    m_display->setFont(QFont("Courier New", 10));
    layout->addWidget(m_display);
    setLayout(layout);
    connect(&m_apiClient, &StockApiClient::stockDataUpdated,
            this, &StockTickerWidget::updateStockData);
    connect(&m_apiClient, &StockApiClient::errorOccurred,
            this, &StockTickerWidget::handleError);
}
References StockApiClient::errorOccurred(), handleError(), m_apiClient, m_display, StockApiClient::stockDataUpdated(), and updateStockData().
~StockTickerWidget()
StockTickerWidget::~StockTickerWidget () default
Member Function Documentation
formatStockInfo()
QString StockTickerWidget::formatStockInfo (const StockData & data) const private
Formats stock info for display.
Parameters
data The stock data.
Returns
Formatted string.
Definition at line 56 of file StockTickerWidget.cpp.
{
    std::stringstream ss;
    // Format basic stock info
    ss << std::left << std::setw(6) << data.symbol << " "
       << std::fixed << std::setprecision(2) << data.price << " ";
    // Color based on change
    if (data.change >= 0) {
        ss << "+" << data.change << " (+" << data.changePercent << "%) ▲";
    } else {
        ss << data.change << " (" << data.changePercent << "%) ▼";
    }
    // Add ASCII chart
    if (!data.history.empty()) {
        ss << "\n" << StockAsciiChart::render(data.history);
    }
    return QString::fromStdString(ss.str());
}
References StockData::change, StockData::changePercent, StockData::history, StockData::price, StockAsciiChart::render(), and StockData::symbol.
Referenced by updateDisplay().
handleError
void StockTickerWidget::handleError (const QString & message) private slot
Handles errors from the API client.
Parameters
message The error message.
Definition at line 36 of file StockTickerWidget.cpp.
{
    m_display->append("Error: " + message);
}
References m_display.
Referenced by StockTickerWidget().
setWatchlist()
void StockTickerWidget::setWatchlist (const Watchlist & watchlist)
Sets the watchlist of stock symbols.
Parameters
watchlist The list of stock symbols to watch.
Definition at line 26 of file StockTickerWidget.cpp.
{
    m_apiClient.setWatchlist(watchlist);
    m_apiClient.startUpdates(5000); // Update every 5 seconds
}
References m_apiClient, StockApiClient::setWatchlist(), and StockApiClient::startUpdates().
Referenced by main().
updateDisplay
void StockTickerWidget::updateDisplay () private slot
Updates the display widget.
Definition at line 40 of file StockTickerWidget.cpp.
{
    QString content;
    for (const auto& [symbol, data] : m_stockData) {
        content += formatStockInfo(data) + "\n\n";
    }
    // Save scroll position
    int scrollPos = m_display->verticalScrollBar()->value();
    m_display->setPlainText(content);
    // Restore scroll position
    m_display->verticalScrollBar()->setValue(scrollPos);
}
References formatStockInfo(), m_display, and m_stockData.
Referenced by updateStockData().
updateStockData
void StockTickerWidget::updateStockData (const StockData & data) private slot
Updates the display when new stock data arrives.
Parameters
data The updated stock data.
Definition at line 31 of file StockTickerWidget.cpp.
{
    m_stockData[data.symbol] = data;
    updateDisplay();
}
References m_stockData, StockData::symbol, and updateDisplay().
Referenced by StockTickerWidget().
Member Data Documentation
m_apiClient
StockApiClient StockTickerWidget::m_apiClient private
API client for fetching stock data.
Definition at line 55 of file StockTickerWidget.h.
Referenced by setWatchlist(), and StockTickerWidget().
m_display
QTextEdit* StockTickerWidget::m_display private
Display widget for stock info.
Definition at line 56 of file StockTickerWidget.h.
Referenced by handleError(), StockTickerWidget(), and updateDisplay().
m_stockData
std::map<std::string, StockData> StockTickerWidget::m_stockData private
Map of symbol to StockData.
Definition at line 58 of file StockTickerWidget.h.
Referenced by updateDisplay(), and updateStockData().
m_watchlist
Watchlist StockTickerWidget::m_watchlist private
List of stock symbols to watch.
Definition at line 57 of file StockTickerWidget.h.
The documentation for this class was generated from the following files:
/media/psanodiya/workspace/cpp/stock-ticker/include/StockTickerWidget.h
/media/psanodiya/workspace/cpp/stock-ticker/src/StockTickerWidget.cpp